# Logistic Regression Implementation

In [1]:
from sklearn.datasets import load_iris

In [2]:
dataset=load_iris()

In [3]:
dataset

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
import pandas as pd
import numpy as np

In [6]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [7]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [8]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [9]:
df['target']=dataset.target

In [10]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [11]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
# Binary Classification
df_copy=df[df['target']!=2]

In [13]:
df_copy.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [14]:
df_copy.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target  
95       1  
96       1  
97       1  
98       1  
99       1

# Independent and Dependent Feature

In [15]:
x=df_copy.iloc[:,:-1]
y=df_copy.iloc[:,-1]

In [16]:
from sklearn.linear_model import LogisticRegression

In [17]:
# Train Test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)

In [18]:
classifier=LogisticRegression()

In [19]:
classifier.fit(x_train,y_train)

LogisticRegression()

In [20]:
classifier.predict_proba(x_test)

array([[0.00144451, 0.99855549],
       [0.01745661, 0.98254339],
       [0.00359664, 0.99640336],
       [0.96427472, 0.03572528],
       [0.93476204, 0.06523796],
       [0.96670676, 0.03329324],
       [0.99197567, 0.00802433],
       [0.03414716, 0.96585284],
       [0.97022597, 0.02977403],
       [0.97501069, 0.02498931],
       [0.94876941, 0.05123059],
       [0.95432911, 0.04567089],
       [0.00502877, 0.99497123],
       [0.98309763, 0.01690237],
       [0.01045624, 0.98954376],
       [0.97788605, 0.02211395],
       [0.00251305, 0.99748695],
       [0.00154296, 0.99845704],
       [0.96995374, 0.03004626],
       [0.95518866, 0.04481134],
       [0.00835685, 0.99164315],
       [0.02378303, 0.97621697],
       [0.95343728, 0.04656272],
       [0.98084327, 0.01915673],
       [0.02881772, 0.97118228],
       [0.97696692, 0.02303308],
       [0.97878312, 0.02121688],
       [0.01706457, 0.98293543],
       [0.96440543, 0.03559457],
       [0.0018048 , 0.9981952 ],
       [0.

In [21]:
# Predictions
y_pred=classifier.predict(x_test)

In [22]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1])

# Confusion matric, Accuracy score, Classification report

In [23]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [24]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[19  0]
 [ 0 14]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        14

    accuracy                           1.00        33
   macro avg       1.00      1.00      1.00        33
weighted avg       1.00      1.00      1.00        33



# Hyperparameter Tuning

In [25]:
# Gridsearchcv
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [26]:
parameters={'penalty':('l1','l2','elasticnet',None),'C':[1,10,20]}

In [27]:
clf=GridSearchCV(classifier,param_grid=parameters,cv=5)

In [28]:
# splitting of train data to validation data
clf.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20],
                         'penalty': ('l1', 'l2', 'elasticnet', None)})

In [29]:
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [30]:
classifier=LogisticRegression(C=1,penalty='l2')

In [31]:
classifier.fit(x_train,y_train)

LogisticRegression(C=1)

In [32]:
# prediction
y_pred=classifier.predict(x_test)
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[19  0]
 [ 0 14]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        14

    accuracy                           1.00        33
   macro avg       1.00      1.00      1.00        33
weighted avg       1.00      1.00      1.00        33



In [33]:
# RandomiszedSearchCV
from sklearn.model_selection import RandomizedSearchCV

In [34]:
random_clf=RandomizedSearchCV(LogisticRegression(),param_distributions=parameters,cv=5)

In [35]:
random_clf.fit(x_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 10, 20],
                                        'penalty': ('l1', 'l2', 'elasticnet',
                                                    None)})

In [36]:
random_clf.best_params_

{'penalty': 'l2', 'C': 10}

In [37]:
classifier=LogisticRegression(C=10,penalty='l2')

In [38]:
classifier.fit(x_train,y_train)

LogisticRegression(C=10)

In [39]:
# prediction
y_pred=classifier.predict(x_test)
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[19  0]
 [ 0 14]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        14

    accuracy                           1.00        33
   macro avg       1.00      1.00      1.00        33
weighted avg       1.00      1.00      1.00        33

